Feeder
team4099/InfiniteRecharge-2021 pull request #3
Opened 2020-11-27 17:51 UTC by vmad18

2020-12-01 22:04 UTC, rbhog reviewed
Everything looks fine, just wanted to make sure that you were only concerned with making the triggers for the feeder. Everything else was the same as last year in ControlBoard

2020-12-01 22:04 UTC, rbhog commented on src/main/kotlin/com/team4099/robot2021/config/ControlBoard.kt
> +  val runFeederIn = Trigger{ operator.dPadDown};
To confirm, you guys were only concerned with changing the feeder controls to triggers right?

2020-12-01 22:14 UTC, rbhog approved these changes
Nice job!

2020-12-01 22:22 UTC, rbhog requested changes
We still need logging

2020-12-02 02:22 UTC, eckshn commented on src/main/kotlin/com/team4099/robot2021/commands/feeder/FeederCommand.kt
> +  }
Add events

2020-12-08 22:47 UTC, rbhog approved these changes
Nice Job!

2020-12-10 22:45 UTC, merged